CTECH-1723: Updates notebooks to work for forked PR's.
finbourne/sample-notebooks pull request #514
Opened 2022-08-19 10:29 UTC by pms1969

Signed-off-by: Paul Saunders <paul.saunders@finbourne.com>

# Pull Request Checklist

- [x] Changes follow the [style guide](https://github.com/finbourne/sample-notebooks/blob/master/docs/FINBOURNE%20notebook%20style%20guide.ipynb)
- [x] Tests pass
- [x] Raised the PR against the `develop` branch

# Description of the PR

Changes focused around enabling access tokens for PR's.  May well need to be merged before the efficacy of the change can be fully realised.

2022-08-25 09:26 UTC, rizwansaeed requested changes

2022-08-25 09:26 UTC, rizwansaeed commented on examples/use-cases/data-quality-control/Custom Entities.ipynb
> -    "if secrets_path is None:\n",
is there are reason we need to remove this? it is useful for when people are running them locally (so they dont have to add and then remove code)?

2022-08-25 12:09 UTC, pms1969 commented on examples/use-cases/data-quality-control/Custom Entities.ipynb
> -    "if secrets_path is None:\n",
Yes, it positively breaks things as I recall.  If people want to run them locally, then they can just add the FBN_SECRETS_PATH env var, no code necessary.

2022-08-25 12:10 UTC, pms1969 commented on examples/use-cases/data-quality-control/Custom Entities.ipynb
> -    "if secrets_path is None:\n",
It was also applied inconsistently.  This snippet of code appeared in about 7 workbooks out of however many we had.  Those workbooks were broken with access tokens.

2022-08-25 13:36 UTC, rizwansaeed commented on examples/use-cases/data-quality-control/Custom Entities.ipynb
> -    "if secrets_path is None:\n",
some editors (I think PyCharm is one) dont currently let you pass env vars through to the Jupyter runner which means you need to edit the notebook locally.

What were the issue you were seeing?

2022-08-26 08:06 UTC, pms1969 commented
Superceded by https://github.com/finbourne/sample-notebooks/pull/518 which doesn't touch the notebooks.

2022-08-26 08:06 UTC, closed without merging